#
# docxprod-pdfilters-docx.yaml
#
filters:
- pandoc-fignos
- pandoc-tablenos
- pandoc-eqnos
- pandoc-secnos
- pdfilter-docx-centertext
- pdfilter-docx-colortext
- pdfilter-docx-pagebreak
- pdfilter-docx-svg2emf
- pdfilter-docx-update-tabwdith
- citeproc
